### ISSUE TITLE
Disk is either full or readonly

### ISSUE THREAD

**Issue by RomjanHossain** [subhra74/xdm-experimental-binaries#50]
I'm seeing the **Disk is either full or readonly** error message after completing downloads, and sometimes even when starting a new download.

Screenshot: ![2023-05-07_19-25](https://user-images.githubusercontent.com/47692261/236680292-f281b904-9e50-4135-ac6e-4b3dfa6c934d.png)

_NOTE: I have 80+GB of free space on my `/home/` directory, which is owned by me, and 300+GB on my HDD, which is also owned by me._

Despite having ample disk space and permission, I am unable to download anything using XDM. I have also tried using different browsers.

I have installed the latest XDM version from the Snap Store using the following command:

`sudo snap install xdman --candidate`

OS: Fedora Linux 38 (Thirty Eight)
xdm version: 8.0.26 BETA

**Comment by ghost** [comment]
This should have been fixed now this happens because xdm is not sandbox friendly and is not designed to work in confined environment but this was fixed in newer versions given that you dont change the download location since the app doesnt allow to download outside it 👍🏻
